language: ruby
install:
  - bundle install

rvm:
  - 2.4
  
script:
  - bundle exec jekyll build -s docs -b /coyote

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
