# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: UseDotNet@2
  displayName: 'Install .NET Core SDK'
  inputs:
    useGlobalJson: true

- task: securedevelopmentteam.vss-secure-development-tools.build-task-policheck.PoliCheck@1
  displayName: 'Run PoliCheck'
  inputs:
    targetType: F

- task: PowerShell@2
  displayName: 'Build Coyote projects'
  inputs:
    targetType: filePath
    filePath: ./Scripts/build.ps1
    failOnStderr: true

- task: PowerShell@2
  displayName: 'Run Coyote Tests'
  inputs:
    targetType: filePath
    filePath: './Scripts/run-tests.ps1'
    failOnStderr: true
  env:
    COYOTE_CLI_TELEMETRY_OPTOUT: 1

- task: PowerShell@2
  displayName: 'Build Coyote NuGet package'
  inputs:
    targetType: filePath
    filePath: './Scripts\create-nuget-packages.ps1'
    failOnStderr: true

- task: PowerShell@2
  displayName: 'Test Coyote.CLI NuGet package'
  inputs:
    targetType: filePath
    filePath: './Scripts/test-cli-package.ps1'
    failOnStderr: true
  env:
    COYOTE_CLI_TELEMETRY_OPTOUT: 1
