# Setup
title:        Coyote
alt-title:    Coyote
tagline:      Coyote - for rapid development of reliable asynchronous code.
baseurl:      "/coyote"

author:
  name:       Microsoft
  url:        https://microsoft.github.io/coyote/

permalink: pretty

source: docs

defaults:
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  learn:
    output: true
    permalink: /:collection/:name
  case-studies:
    output: true
    permalink: /:collection/:name
  portfolio:
    output: true
    permalink: /:collection/:name

plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-relative-links

relative_links:
  enabled:     true
  collections: true

# Handling Reading
safe:         false
include:      [".htaccess"]
#exclude:      [_learn/ref]
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"

# Conversion
markdown:    kramdown
highlighter: rouge

# Markdown Processors
rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input:          GFM
  auto_ids:       true
  footnote_nr:    1
  entity_output:  as_char
  toc_levels:     1..6
  smart_quotes:   lsquo,rsquo,ldquo,rdquo
  enable_coderay: false

  syntax_highlighter_opts:
    coderay_wrap:              div
    coderay_line_numbers:      inline
    coderay_line_number_start: 1
    coderay_tab_width:         4
    coderay_bold_every:        10
    coderay_css:               style
