# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Build and Test Samples CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
  workflow_dispatch:
    branches: [ main ]
jobs:
  build-and-test-samples:
    name: Build and test Coyote samples
    strategy:
      matrix:
        platform: [ windows-latest, ubuntu-latest, macos-latest ]
    runs-on: ${{ matrix.platform }}
    env:
      COYOTE_CLI_TELEMETRY_OPTOUT: 1
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET 6.0 SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'
      - name: Build and test Coyote samples
        run: |
          ./Samples/Scripts/build-tests.ps1 -local $true
          dotnet ./Samples/Common/bin/net6.0/TestDriver.dll
        shell: pwsh
