# Copyright (c) Microsoft Corporation.
# Licensed under the MIT License.

name: Coyote Performance CI
on:
  push:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - '**.md'
jobs:
  build-and-test:
    name: Performance Test Coyote
    runs-on: self-hosted
    env:
      COYOTE_CLI_TELEMETRY_OPTOUT: 1
      AZURE_COSMOSDB_ENDPOINT: ${{ secrets.AZURE_COSMOSDB_ENDPOINT }}
      AZURE_STORAGE_PRIMARY_KEY: ${{ secrets.AZURE_STORAGE_PRIMARY_KEY }}
      LocalBenchmarks: ${{ secrets.LocalBenchmarks }}
    steps:
      - uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2.8.0
      - name: Setup NuGet.exe
        uses: NuGet/setup-nuget@296fd3ccf8528660c91106efefe2364482f86d6f # v1.2.0
        with:
          nuget-version: '6.x'
      - name: Setup .NET 8.0 SDK
        uses: actions/setup-dotnet@871f041373faaad213a635d9afb62905ec029bbb # v1.10.1
        with:
          dotnet-version: '8.0.x'
      - name: Setup Powershell
        run: ./Scripts/install-pwsh.cmd
      - name: Build Coyote projects
        run: ./Scripts/build.ps1 -ci
        shell: pwsh
      - name: Run Performance Benchmark 1
        run: ./Scripts/run-benchmarks.ps1
        shell: pwsh
      - name: Run Performance Benchmark 2
        run: ./Scripts/run-benchmarks.ps1
        shell: pwsh
      - name: Run Performance Benchmark 3
        run: ./Scripts/run-benchmarks.ps1
        shell: pwsh
      - name: Run Performance Benchmark 4
        run: ./Scripts/run-benchmarks.ps1
        shell: pwsh
      - name: Run Performance Benchmark 5
        run: ./Scripts/run-benchmarks.ps1
        shell: pwsh
